### ISSUE TITLE
Typo: '한국인' should be '한국어'

### ISSUE THREAD

**Issue by hwahyeon** [LinkTheCoder/Portfolio#1]
Hi!
I wanted to mention a small detail: "한국인" refers to Korean people, and "한국어" means the Korean language.

By the way, I must say that I really like your design work, it's truly impressive!

Warm regards

**Comment by LinkTheCoder** [comment]
Oh, I know the different between 한국인 and 한국어, I just somehow made a small typo 😅

Thanks for telling me and it makes me happy you liked the design 😁
